name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Platane/snk@master
        with:
          github_user_name: dhanush-sathish
          outputs: |
                dist/github-contribution-grid-snake.svg
                dist/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push snake
        uses: EndBug/add-and-commit@v9
        with:
          add: "dist/*"
          message: "Generate Snake"
          push: true
